# Generated by Django 5.1.6 on 2025-02-14 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default='licor', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='administracion.categoria'),
        ),
    ]
