# Generated by Django 5.1.6 on 2025-02-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_categoria_actualizado_por_categoria_creado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaNombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Tu empresa', max_length=25, null=True)),
                ('correo', models.EmailField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
            ],
        ),
    ]
