# Generated by Django 5.1.6 on 2025-02-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_empresanombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresanombre',
            name='nit',
            field=models.IntegerField(default=123456789, max_length=50, null=True),
        ),
    ]
