# Generated by Django 5.1.6 on 2025-02-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_empresanombre_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresanombre',
            name='nit',
            field=models.IntegerField(default='123456789', null=True),
        ),
    ]
