# Generated by Django 5.1.6 on 2025-02-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_alter_empresanombre_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresanombre',
            name='nit',
            field=models.IntegerField(blank=True, default='123456789', null=True),
        ),
    ]
