# Generated by Django 5.1.6 on 2025-02-28 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_historialproducto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialproducto',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historialproducto',
            name='detalle_cambio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historialproducto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='historial/'),
        ),
        migrations.AlterField(
            model_name='historialproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.producto'),
        ),
        migrations.AlterField(
            model_name='historialproducto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
