# Generated by Django 5.1.6 on 2025-02-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_historialproducto_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialproducto',
            name='nombre_producto',
            field=models.CharField(max_length=255),
        ),
    ]
