# Generated by Django 5.1.6 on 2025-02-16 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_categoria_actualizado_por_categoria_creado_por_and_more'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.venta')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(through='trabajadores.VentaProducto', to='administracion.producto'),
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
