# Generated by Django 5.1.6 on 2025-02-16 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_ventaproducto_venta_productos_delete_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventaproducto_set', to='trabajadores.venta'),
        ),
    ]
