# Generated by Django 5.1.6 on 2025-02-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_categoria_actualizado_por_categoria_creado_por_and_more'),
        ('trabajadores', '0003_alter_ventaproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='datos_producto',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.producto'),
        ),
    ]
