# Generated by Django 5.1.6 on 2025-02-25 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_empresanombre'),
        ('trabajadores', '0004_ventaproducto_datos_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaproducto',
            name='datos_producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto'),
        ),
    ]
