# Generated by Django 5.1.6 on 2025-02-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0006_historialventa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialVenta',
        ),
    ]
