# Generated by Django 5.1.6 on 2025-02-28 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_alter_historialproducto_nombre_producto'),
        ('trabajadores', '0007_delete_historialventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='nombre_producto',
            field=models.CharField(default='Producto eliminado', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.producto'),
        ),
    ]
