# Generated by Django 5.1.6 on 2025-03-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0008_ventaproducto_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.CharField(max_length=15),
        ),
    ]
