# Generated by Django 5.1.6 on 2025-06-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0009_alter_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='devolucion',
            field=models.BooleanField(default=False),
        ),
    ]
